version: 2.1

workflows:
  testing-ssh:
    jobs:
      - testing-ssh

jobs:
  testing-ssh:
    # macos:
    #   xcode: 13.4.0
    docker:
     # - image: cimg/openjdk:18.0.1-node
      - image: circleci/node:10.16.3
    resource_class: medium
    # shell: /bin/bash --login -eo pipefail
    steps:
        - checkout
        - run: echo "testing"
