version: 2.1

workflows:
  breaking-curl:
    jobs:
      - breaking-curl

jobs:
  breaking-curl:
     macos:
       xcode: 13.4.0
    docker:
     # - image: cimg/openjdk:18.0.1-node
     # - image: cimg/base:2022.06
    resource_class: medium
    # shell: /bin/bash --login -eo pipefail
    steps:
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      - run: curl --connect-timeout 120.0 --max-time 120.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
      
      
#version: 2.1
# ro
#
#jobs:
#  runner:
#    machine: true
#    resource_class: logan/medium
#    steps:
#      - run: echo "Hi I'm on Runners!"
#
#workflows:
#  testing:
#    jobs:
#      - runner
